### ISSUE TITLE
Changing title

### ISSUE THREAD

**Issue by wcastand** [parro-it/hyperterm-title#1]
Hi,
I don't know if you can help but i'm using hyperterm and zsh and i tried to use your plugin and i have a small issue. the title is too big !! :P 
<img width="558" alt="capture d ecran 2016-07-20 a 10 57 30" src="https://cloud.githubusercontent.com/assets/2178244/16981005/f69687f6-4e68-11e6-925d-add493d3125f.png">

Do you have any idea how to change the title to just the current directory for example ?
i tried in my .zshrc:
`precmd () {print -Pn "\e]0;%n@%m: %~\a"}`
`echo -ne "\e]1;this is the title\a"`

I also tried to disable auto title but once i do that, nothing appears at all :/
`DISABLE_AUTO_TITLE="true"`

If someone know how to correct that, i will be really happy :D

**Comment by parro-it** [comment]
Hi @wcastand . Regarding how to set title in zsh, have a look at @sindresorhus [pure prompt](https://github.com/sindresorhus/pure/blob/master/pure.zsh#L87).

Regarding the title length, I see two way here:

1) I can cut the title string I receive from the shell before displaying it, and showing ellipsis at the end.
We could use a predefined maximum length, or add a config variable to customize the length.

2) We can customize the length of the header element using css, either by changing `hyperterm` core or by wrapping the header element.

I'm unsure what could be the best way...

Regarding the empty title when you use DISABLE_AUTO_TITLE="true", I think I could display the default  `hyperterm` title when I receive an empty string from the shell...

**Comment by wcastand** [comment]
I used pure.zsh and it works perfectly (even better than expected) thanks 👍
