### ISSUE TITLE
Use ~ instead of $HOME on OSX

### ISSUE THREAD

**Issue by davidascher** [parro-it/hyperterm-title#2]
I'm not sure why, but at least on OSX El Capitan, I'm not seeing ~ show up in the title bar (whereas it shows up in the prompt).

<img width="710" alt="screenshot 2016-07-23 13 52 28" src="https://cloud.githubusercontent.com/assets/51278/17080245/cab8c90c-50dc-11e6-9a32-e28e0cf2083f.png">

Any advice?

**Comment by parro-it** [comment]
This plugin does not directly change the title of the tabs, it set it to whatever string the shell ask for, so the lack of tile in your example should depend on your bash setup.

The screenshots in readme are taken using [pure prompt](https://github.com/sindresorhus/pure) by @sindresorhus. try to coinfigure it and see if this solve the problem.

**Comment by sindresorhus** [comment]
@parro-it Many users set up their prompt incorrectly though, so would be nice to just handle it for them. You could easily do so by running the path through [`tildify`](https://github.com/sindresorhus/tildify).

**Comment by parro-it** [comment]
@sindresorhus nice idea!

**Comment by davidascher** [comment]
using pure+zsh does fix it, but yeah, I like what @sindreorhus says (and
didn't know about tildify!)

**Comment by parro-it** [comment]
After more thinking, I think that could be problems using `tildify`.

We are supposing that the user running `hyperterm` it's the same running the shell. 

But in the shell we can `sudo` or ssh to another server, in these cases we risk to change the title to ~ while we are not in the home of the actual user. 

What do you think?

**Comment by sindresorhus** [comment]
`tildify` only tildifies if the path is in the current user's home directory. So I don't really see the problem.

**Comment by parro-it** [comment]
> tildify only tildifies if the path is in the current user's home directory. So I don't really see the problem.

Maybe I have to look at `tildify` in more depth, but how can you know which user is running in the shell process? I suppose you look at the home directory of the user that runs the Electron process (the one in which `tildify` itself is running`).

E.g.:

``` bash
$ whoami
parro-it
$ cd /home/parro-it
// `tildify` now correctly think I'm in my home directory
$ sudo -s
$ cd /root
// How can `tildify` know I'm in root home directory now?
$ cd /home/parro-it
// `tildify` now incorrectly think I'm in my home directory, while I'm not?
```

Maybe it's a false problem... I havn't to checked how other terminals works in this case

**Comment by parro-it** [comment]
I checked how it works on Linux, if I change user on a shell using `su` command, the shell correctly report `~` as the home of the new user.

The shell process owner change to the new user, so we are able to detect the situation, but I think a change in `tildify` would be needed to allow specify a custom user.
