### ISSUE TITLE
/user/bin/env: 'node': no such file or directory

### ISSUE THREAD

**Issue by RomuloPBenedetti** [parro-it/hyperterm-title#4]
On Ubuntu it is installed as `/usr/bin/nodejs`.
A quick solution is `ln -s /usr/bin/nodejs /usr/bin/node` but user shouldn't need to search it :)

**Comment by parro-it** [comment]
This plugin doesn't call node in any point: where are you getting this error? 

Moreover,  you should use the node js apt repository to install node on Ubuntu, it setup the node bin with the correct name.

**Comment by RomuloPBenedetti** [comment]
Sure, it was on the install, I'm just pointing that you could point this on `readme` :)

**Comment by parro-it** [comment]
> Sure, it was on the install, I'm just pointing that you could point this on readme :)

Do you mean when you install hpm?

**Comment by RomuloPBenedetti** [comment]
Yes, your readme point to `npm install -g hpm-cli` and it create the binary as `/usr/bin/nodejs`
