### ISSUE TITLE
Title not changing

### ISSUE THREAD

**Issue by ghost** [parro-it/hyperterm-title#6]
Installed it correctly, added it to my ``plugins`` array, no errors in the devtools, but the title is still always ``shell``.

OS: Windows 10
Hyperterm version: latest
Plugin version: latest
Plugins array:  ``plugins: ['hyper-material-box', 'hyperline', 'hyperterm-working-directory', 'hyperterm-title']``
Screenshot: https://i.imgur.com/Y0TAFdH.png

**Comment by parro-it** [comment]
This plugin [is deprecated](https://github.com/parro-it/hyperterm-title/issues/5), its functionality are noew buitin in hyper

**Comment by ghost** [comment]
Oh. Then it isn't working for me on Win10 either. Thanks!
